FROM swift:4.0

RUN swift --version

RUN apt-get update
RUN apt-get install -y postgresql libpq-dev

WORKDIR /app

COPY .build/dependencies-state.json ./.build/dependencies-state.json
COPY .env ./
COPY Makefile ./
COPY Package.resolved ./
COPY Packages ./Packages

COPY Package.swift ./
RUN swift package update

COPY Sources ./Sources
RUN swift build --configuration release

CMD ./.build/release/pointfreeco
