version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    environment:
      POSTGRES_USER: pointfreeco
    image: postgres
    ports:
      - '5432:5432'
    restart: always
